services:
  nextcloud:
    image: nextcloud:latest
    ports:
      - 0.0.0.0:8080:80
    restart: unless-stopped
    volumes:
      - /data/nextcloud/data:/var/www/html/data
      - /data/nextcloud/config:/var/www/html/config
      - /data/nextcloud:/var/www/html
    environment:
      - TZ=Asia/Shanghai

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - "8096:8096"
    environment:
      - TZ=Asia/Shanghai
      - PUID=1000
      - PGID=1000
    volumes:
      - /data/jellyfin/config:/config
      - /data/nextcloud/data:/nextcloud
      - /data/rargb:/rargb

  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    environment:
      - TZ=Asia/Shanghai
      - Docker_MODS=linuxserver/mods:universal-calibre
    ports:
      - "8083:8083"
    volumes:
      - /data/calibre/conf:/config
      - /data/nextcloud/data/lidaning/files:/nextcloud
    restart: unless-stopped

  # obsidian:
  #   image: lscr.io/linuxserver/obsidian:latest
  #   ports:
  #     - "3000:3000"
  #     - "3001:3001"
  #   volumes:
  #     - /data/obsidian/config:/config
  #     - /data/obsidian/data:/data
  #   restart: unless-stopped
