services:
  nextcloud:
    image: nextcloud
    ports:
      - 0.0.0.0:8080:80
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - "8096:8096"
    environment:
    - TZ=Asia/Shanghai
    - PUID=1000
    - PGID=1000
    volumes:
    - ./jellyfin_config:/config
    - ./jellyfin_cache:/cache

    - bd030fb5679919783a8d22cdebbbb4a16782a766d89dd9a0e79be0e4079b1dfb:/media
    - d:\rargb:/local_media

  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    environment:
      - PUID=33
      - PGID=33
      - TZ=Asia/Shanghai
      - Docker_MODS=linuxserver/mods:universal-calibre
    ports:
      - "8083:8083"
    volumes:
      - ./calibre-conf:/config
      - bd030fb5679919783a8d22cdebbbb4a16782a766d89dd9a0e79be0e4079b1dfb:/nextcloud
    restart: unless-stopped




volumes:
  bd030fb5679919783a8d22cdebbbb4a16782a766d89dd9a0e79be0e4079b1dfb:
    external: true
  host_volume:
    external: true

